export const INSPECT_VOLUME = 'INSPECT_VOLUME';
export const FETCH_VOLUMES = 'FETCH_VOLUMES';

export const INSPECT_NETWORK = 'INSPECT_NETWORK';
export const FETCH_NETWORKS = 'FETCH_NETWORKS';

export const INSPECT_IMAGE = 'INSPECT_IMAGE';
export const FETCH_IMAGES = 'FETCH_IMAGES';
