export const VOLUME = {
  INSPECT: 'INSPECT_VOLUME',
  FETCH: 'FETCH_VOLUMES',
  PRUNE: 'PRUNE_VOLUMES'
};

export const NETWORK = {
  INSPECT: 'INSPECT_NETWORK',
  FETCH: 'FETCH_NETWORKS',
  PRUNE: 'PRUNE_NETWORKS'
};

export const CONTAINER = {
  INSPECT: 'INSPECT_CONTAINER',
  FETCH: 'FETCH_CONTAINERS',
  PRUNE: 'PRUNE_CONTAINERS'
};
