export const COMMON = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

export const VOLUME = {
  INSPECT: 'INSPECT_VOLUME',
  FETCH: 'FETCH_VOLUMES',
  PRUNE: 'PRUNE_VOLUMES'
};

export const NETWORK = {
  INSPECT: 'INSPECT_NETWORK',
  FETCH: 'FETCH_NETWORKS',
  PRUNE: 'PRUNE_NETWORKS'
};

export const CONTAINER = {
  INSPECT: 'INSPECT_CONTAINER',
  FETCH: 'FETCH_CONTAINERS',
  PRUNE: 'PRUNE_CONTAINERS'
};

export const IMAGE = {
  INSPECT: 'INSPECT_IMAGE',
  FETCH: 'FETCH_IMAGES',
  PRUNE: 'PRUNE_IMAGES',
  TAG: 'TAG_IMAGES',
  DELETE: 'DELETE_IMAGE'
};
